### ISSUE TITLE
Node property not being returned in Table view

### ISSUE THREAD

**Issue by joefagan** [apache/incubator-age-viewer#16]
**Describe the bug**
match (n) return n.name
does not show the value of the property  
match (n) return collect(n.name) works fine!!

**To Reproduce**
Create a new graph as follows;
```
-- drop graph for cleanup between tests
SELECT * FROM ag_catalog.drop_graph('test_graph', true);

-- start from a new graph
-- create parent connected to 2 children with multiple properties
SELECT * FROM create_graph('test_graph');
SELECT * FROM cypher('test_graph', $$
    CREATE (p:person {name: 'parent'})
    CREATE (c1:person {name: 'child1', age: 11 })
    CREATE (c2:person {name: 'child2', age: 12 })
    CREATE (p)-[:connect {type: 'is parent'}]->(c1)
    CREATE (p)-[:connect {type: 'is parent'}]->(c2)
    RETURN p
$$) as (p agtype);
```
run this query
```
SELECT * from cypher('test_graph', $$
          MATCH (n)
          RETURN n.name
$$) as (n agtype);
```
**Expected behavior**
    n
----------
 "parent"
 "child1"
 "child2"
(3 rows)

**Screenshots** 
actual behaviour - property not displayed.
![image](https://user-images.githubusercontent.com/48284776/144880198-b2d86c90-7d57-4cde-993b-cbbd775e6d8b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - 
Edition	Windows 10 Home
Version	20H2
Installed on	‎27/‎03/‎2021
OS build	19042.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

Google chrome

Version 96.0.4664.45 (Official Build) (64-bit)

**Additional context**
docker run --publish=3001:3001 --name=agviewer bitnine/agviewer:latest
docker run -it -e POSTGRES_PASSWORD=mypassword -p 5432:5432 joefagan/incubator-age

**Comment by emotionbug** [comment]
This commit will be fix.
https://github.com/apache/incubator-age-viewer/commit/d4b031088cbb08e9b703bc011ca198f4553c0dcc
