### ISSUE TITLE
can't understand query error

### ISSUE THREAD

**Issue by ChipNowacek** [apache/incubator-age-viewer#9]
I'm embarrassed I can't yet interpret this output. The query was generated by clicking the middle node label. 
<img width="1327" alt="Screen Shot 2021-10-09 at 10 02 54 PM" src="https://user-images.githubusercontent.com/3668197/136680149-c3663baf-320a-435d-acbe-15875eb9ddb1.png">
Should I be asking this somewhere else? If so, please forgive me.

**Comment by joefagan** [comment]
Please supply all the code you used to create the graph including the query that failed, so as to help reproduce the error.
 
Please confirm AGE extension version with
```
SELECT extname, extversion FROM pg_extension WHERE extname='age';
```

It could be an AGViewer but more likely an AGE issue so you may have to ask in a couple of places.
You can email users@age.apache.org or dev@age.apache.org
You may have to subscribe to see responses at https://lists.apache.org/list.html?users@age.apache.org or https://lists.apache.org/list.html?dev@age.apache.org

**Comment by emotionbug** [comment]
Are you use docker?

**Comment by david-m-m** [comment]
I'm not sure why this has been closed. 
Just for completeness here are the steps to reproduce:

1. Run docker containers
`$ docker run -it -e POSTGRES_PASSWORD=svcTree --expose 5432 sorrell/apache-age
$ docker run -ti --expose 3001 bitnine/agviewer`
Both running latest tag (as of this week, 2021-11-22)

2. Create graph and some data
```
SELECT * FROM create_graph('test');
SELECT * FROM cypher('test', $$ CREATE (john:Person {name: 'John'}) $$) as (r agtype);
SELECT * FROM cypher('test', $$ CREATE (j:Person {name: 'Jack'}) $$) as (r agtype);
SELECT * from cypher('test', $$ MATCH (a:Person),(b:Person) WHERE a.name='John' AND b.name='Jack' CREATE (a)-[r:Friend]->(b) RETURN type(r) $$) as (r agtype);
```

3. Open age-viewer in your browser and connect to database and graph
4. Click on "Node Label -> Person" (Query: `SELECT * from cypher('test', $$ MATCH (V:Person) RETURN V $$) as (V agtype);` )
This one works and just shows the two nodes (no relation)
5. Click on "Edge Label -> Friend" (Query: `SELECT * from cypher('test', $$ MATCH (V)-[R:Friend]-(V2) RETURN V,R,V2 $$) as (V agtype, R agtype, V2 agtype);` )
This one results in the error.
6. Update the relation (set a property):
`SELECT * from cypher('test', $$ MATCH (a:Person)-[r:Friend]->(b:Person) WHERE a.name='John' AND b.name='Jack' SET r.type='close' RETURN r $$) as (r agtype);`
7. Click on "Friend" again: Voilà, graph shows including relation.

**Comment by david-m-m** [comment]
@emotionbug last comment FYI

**Comment by emotionbug** [comment]
@david-m-m Ok. I'll rechecking it.

**Comment by emotionbug** [comment]
The problem was already solved, but docker didn't update.  So, I updated yesterday.  Remove any remaining images locally and try again

**Comment by david-m-m** [comment]
Thanks a lot @emotionbug
The updated Docker image works just fine. :+1:
